Dev 1.3
Thurion/EDSM-RSE-for-EDMC pull request #53
Opened 2020-06-25 22:31 UTC by RapidfireCRH

Moving debug messages to one method in RseData

2020-06-25 23:08 UTC, Thurion requested changes

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +    def printdebug(str, msgdebug):
move into RseData class

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +    debug = False
move into rseData class. I'm not sure if the value is actually stored.
It's also really out of place there :)

2020-06-25 23:08 UTC, Thurion commented on Backgroundworker.py
> +            RseData.printdebug("EDSM-RSE: Stopping RSE background timer", True)
remove EDSM-RSE

2020-06-25 23:08 UTC, Thurion commented on Backgroundworker.py
> +        RseData.printdebug("EDSM-RSE: timerTask triggered", True)
remove EDSM-RSE

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            RseData.printdebug("EDSM-RSE: Using cached system list for distances. Radius was set to {}".format(self.rseData.calculateRadius()), True)
remove EDSM-RSE

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            RseData.printdebug("EDSM-RSE: arrived in {}".format(system.name), True)
remove EDSM-RSE

2020-06-25 23:08 UTC, Thurion commented on load.py
> +    RseData.setdebug(this.debug.get())
```suggestion
    this.rseData.debug(this.debug.get())
```

2020-06-25 23:08 UTC, Thurion commented on load.py
> +    RseData.setdebug(this.debug.get())
```suggestion
    this.rseData.debug(this.debug.get())
```

2020-06-25 23:08 UTC, Thurion commented on load.py
> +    settings = (this.clipboard.get() << 5) | (this.overwrite.get() << 6) | ((not this.edsmBodyCheck.get()) << 7) | (this.debug.get() <<8)
```suggestion
    settings = (this.clipboard.get() << 5) | (this.overwrite.get() << 6) | ((not this.edsmBodyCheck.get()) << 7) | (this.debug.get() << 8)
```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +    def setdebug(set):
setdebug function not required when part of RseData class

2020-06-25 23:08 UTC, Thurion commented on Backgroundworker.py
> +        RseData.printdebug("timerTask triggered", True)
```suggestion
        self.rseData.printdebug("timerTask triggered", True)

```

2020-06-25 23:08 UTC, Thurion commented on Backgroundworker.py
> +            RseData.printdebug("Stopping RSE background timer", True)
```suggestion
            self.rseData.printdebug("Stopping RSE background timer", True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +            RseData.printdebug("Local cache database could not be opened", True)
```suggestion
            self.printdebug("Local cache database could not be opened", True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +            RseData.printdebug("Found too few systems, increasing radius to {1}".format(numberOfSystems, self.calculateRadius()), True)
```suggestion
            self.printdebug("Found too few systems, increasing radius to {1}".format(numberOfSystems, self.calculateRadius()), True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +            RseData.printdebug("Found too many systems, decreasing radius to {1}".format(numberOfSystems, self.calculateRadius()), True)
```suggestion
            self.printdebug("Found too many systems, decreasing radius to {1}".format(numberOfSystems, self.calculateRadius()), True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +                RseData.printdebug("error fetching nearby systems. HTTP code: " + url.getcode(), True)
```suggestion
                self.printdebug("error fetching nearby systems. HTTP code: " + url.getcode(), True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +            RseData.printdebug("error fetching nearby systems: " + str(e), True)
```suggestion
            self.printdebug("error fetching nearby systems: " + str(e), True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +        RseData.printdebug("found {systems} systems within {radius} ly".format(systems=len(systems), radius=self.calculateRadius()), True)
```suggestion
        self.printdebug("found {systems} systems within {radius} ly".format(systems=len(systems), radius=self.calculateRadius()), True)

```

2020-06-25 23:08 UTC, Thurion commented on RseData.py
> +    def printdebug(str, msgdebug):
```suggestion
    def printdebug(self, str, msgdebug):

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +        RseData.printdebug("{} didn't implement execute".format(self.__class__.__name__), True)
```suggestion
        self.rseData.printdebug("{} didn't implement execute".format(self.__class__.__name__), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +        RseData.printdebug("{} didn't implement fireEvent".format(self.__class__.__name__), True)
```suggestion
        self.rseData.printdebug("{} didn't implement fireEvent".format(self.__class__.__name__), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +        RseData.printdebug("adding {count} systems to removal filter: {systems}".format(count=len(removeMe), systems=[x.name for x in removeMe]), True)
```suggestion
        self.rseData.printdebug("adding {count} systems to removal filter: {systems}".format(count=len(removeMe), systems=[x.name for x in removeMe]), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +        RseData.printdebug("querying EDSM for {} systems".format(len(params)), True)
```suggestion
        self.rseData.printdebug("querying EDSM for {} systems".format(len(params)), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +                RseData.printdebug("EDSM query call failed.", True)
```suggestion
                self.rseData.printdebug("EDSM query call failed.", True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            RseData.printdebug("arrived in {}".format(system.name), True)
```suggestion
            self.rseData.printdebug("arrived in {}".format(system.name), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            RseData.printdebug("Using cached system list for distances. Radius was set to {}".format(self.rseData.calculateRadius()), True)
```suggestion
            self.rseData.printdebug("Using cached system list for distances. Radius was set to {}".format(self.rseData.calculateRadius()), True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            print("querying EDSM for bodies of system {}".format(self.systemName))
missed call of debug output

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            RseData.printdebug("EDSM body count call failed.", True)
```suggestion
            self.rseData.printdebug("EDSM body count call failed.", True)

```

2020-06-25 23:08 UTC, Thurion commented on BackgroundTask.py
> +            print("querying EDSM for bodies of system {}".format(self.systemName))
```suggestion
        self.rseData.printdebug("querying EDSM for bodies of system {}".format(self.systemName))

```

2020-06-26 18:09 UTC, RapidfireCRH commented on BackgroundTask.py
> +            RseData.printdebug("EDSM-RSE: arrived in {}".format(system.name), True)
This change was completed

2020-06-26 18:10 UTC, RapidfireCRH commented on BackgroundTask.py
> +            RseData.printdebug("EDSM-RSE: Using cached system list for distances. Radius was set to {}".format(self.rseData.calculateRadius()), True)
This change was completed

2020-06-26 18:11 UTC, RapidfireCRH commented on Backgroundworker.py
> +        RseData.printdebug("EDSM-RSE: timerTask triggered", True)
This change was completed

2020-06-26 18:11 UTC, RapidfireCRH commented on Backgroundworker.py
> +            RseData.printdebug("EDSM-RSE: Stopping RSE background timer", True)
This change was completed

2020-06-26 18:59 UTC, Thurion approved these changes

2020-06-26 18:59 UTC, merged